// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260326183830_UpdateRowVersion")]
    partial class UpdateRowVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DropoffPointId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PickupPointId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DropoffPointId");

                    b.HasIndex("PickupPointId");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Domain.Entities.BookingDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("SeatId");

                    b.ToTable("BookingDetails");
                });

            modelBuilder.Entity("Domain.Entities.Bus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SeatCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusTypeId");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CompanyName = "Phương Trang (FUTA)",
                            PlateNumber = "51B-123.45",
                            SeatCount = 44,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            BusTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CompanyName = "Thành Bưởi",
                            PlateNumber = "51B-678.90",
                            SeatCount = 9,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.BusType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SeatCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BusTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "VIP Limousine",
                            Name = "Limousine",
                            SeatCount = 9
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Sleeper Bus Standard",
                            Name = "Giường nằm",
                            SeatCount = 44
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Standard Seat Bus",
                            Name = "Ghế ngồi",
                            SeatCount = 45
                        });
                });

            modelBuilder.Entity("Domain.Entities.CmsConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConfigKey")
                        .IsUnique();

                    b.ToTable("CmsConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConfigKey = "homepage_v1",
                            ContentJson = "{}",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Domain.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DistanceKm")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Points")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Domain.Entities.RouteStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DistanceFromOriginKm")
                        .HasColumnType("float");

                    b.Property<int>("OffsetMinutes")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("LocationId");

                    b.ToTable("RouteStops");
                });

            modelBuilder.Entity("Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ColumnNumber")
                        .HasColumnType("int");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LockExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LockedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("Domain.Entities.SeatTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ColumnNumber")
                        .HasColumnType("int");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusTypeId");

                    b.ToTable("SeatTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000001"),
                            BusTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ColumnNumber = 1,
                            Floor = 1,
                            RowNumber = 1,
                            SeatNumber = "L01",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000002"),
                            BusTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ColumnNumber = 2,
                            Floor = 1,
                            RowNumber = 1,
                            SeatNumber = "L02",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000003"),
                            BusTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ColumnNumber = 3,
                            Floor = 1,
                            RowNumber = 1,
                            SeatNumber = "L03",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000004"),
                            BusTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ColumnNumber = 1,
                            Floor = 1,
                            RowNumber = 2,
                            SeatNumber = "L04",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000005"),
                            BusTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ColumnNumber = 2,
                            Floor = 1,
                            RowNumber = 2,
                            SeatNumber = "L05",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000006"),
                            BusTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ColumnNumber = 3,
                            Floor = 1,
                            RowNumber = 2,
                            SeatNumber = "L06",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000007"),
                            BusTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ColumnNumber = 1,
                            Floor = 1,
                            RowNumber = 3,
                            SeatNumber = "L07",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000008"),
                            BusTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ColumnNumber = 2,
                            Floor = 1,
                            RowNumber = 3,
                            SeatNumber = "L08",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000009"),
                            BusTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ColumnNumber = 3,
                            Floor = 1,
                            RowNumber = 3,
                            SeatNumber = "L09",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 1,
                            Floor = 1,
                            RowNumber = 1,
                            SeatNumber = "A01",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 2,
                            Floor = 1,
                            RowNumber = 1,
                            SeatNumber = "A02",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 3,
                            Floor = 1,
                            RowNumber = 1,
                            SeatNumber = "A03",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 1,
                            Floor = 1,
                            RowNumber = 2,
                            SeatNumber = "A04",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 2,
                            Floor = 1,
                            RowNumber = 2,
                            SeatNumber = "A05",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 3,
                            Floor = 1,
                            RowNumber = 2,
                            SeatNumber = "A06",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 1,
                            Floor = 1,
                            RowNumber = 3,
                            SeatNumber = "A07",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 2,
                            Floor = 1,
                            RowNumber = 3,
                            SeatNumber = "A08",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 3,
                            Floor = 1,
                            RowNumber = 3,
                            SeatNumber = "A09",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 1,
                            Floor = 1,
                            RowNumber = 4,
                            SeatNumber = "A10",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 2,
                            Floor = 1,
                            RowNumber = 4,
                            SeatNumber = "A11",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 3,
                            Floor = 1,
                            RowNumber = 4,
                            SeatNumber = "A12",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 1,
                            Floor = 1,
                            RowNumber = 5,
                            SeatNumber = "A13",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 2,
                            Floor = 1,
                            RowNumber = 5,
                            SeatNumber = "A14",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 3,
                            Floor = 1,
                            RowNumber = 5,
                            SeatNumber = "A15",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 1,
                            Floor = 1,
                            RowNumber = 6,
                            SeatNumber = "A16",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 2,
                            Floor = 1,
                            RowNumber = 6,
                            SeatNumber = "A17",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000018"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 3,
                            Floor = 1,
                            RowNumber = 6,
                            SeatNumber = "A18",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000019"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 1,
                            Floor = 2,
                            RowNumber = 1,
                            SeatNumber = "B01",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000020"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 2,
                            Floor = 2,
                            RowNumber = 1,
                            SeatNumber = "B02",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000021"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 3,
                            Floor = 2,
                            RowNumber = 1,
                            SeatNumber = "B03",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000022"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 1,
                            Floor = 2,
                            RowNumber = 2,
                            SeatNumber = "B04",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000023"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 2,
                            Floor = 2,
                            RowNumber = 2,
                            SeatNumber = "B05",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000024"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 3,
                            Floor = 2,
                            RowNumber = 2,
                            SeatNumber = "B06",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000025"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 1,
                            Floor = 2,
                            RowNumber = 3,
                            SeatNumber = "B07",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000026"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 2,
                            Floor = 2,
                            RowNumber = 3,
                            SeatNumber = "B08",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000027"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 3,
                            Floor = 2,
                            RowNumber = 3,
                            SeatNumber = "B09",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000028"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 1,
                            Floor = 2,
                            RowNumber = 4,
                            SeatNumber = "B10",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000029"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 2,
                            Floor = 2,
                            RowNumber = 4,
                            SeatNumber = "B11",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000030"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 3,
                            Floor = 2,
                            RowNumber = 4,
                            SeatNumber = "B12",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000031"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 1,
                            Floor = 2,
                            RowNumber = 5,
                            SeatNumber = "B13",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000032"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 2,
                            Floor = 2,
                            RowNumber = 5,
                            SeatNumber = "B14",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000033"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 3,
                            Floor = 2,
                            RowNumber = 5,
                            SeatNumber = "B15",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000034"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 1,
                            Floor = 2,
                            RowNumber = 6,
                            SeatNumber = "B16",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000035"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 2,
                            Floor = 2,
                            RowNumber = 6,
                            SeatNumber = "B17",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000036"),
                            BusTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColumnNumber = 3,
                            Floor = 2,
                            RowNumber = 6,
                            SeatNumber = "B18",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000001"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 1,
                            Floor = 1,
                            RowNumber = 1,
                            SeatNumber = "S01",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000002"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 2,
                            Floor = 1,
                            RowNumber = 1,
                            SeatNumber = "S02",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000003"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 3,
                            Floor = 1,
                            RowNumber = 1,
                            SeatNumber = "S03",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000004"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 4,
                            Floor = 1,
                            RowNumber = 1,
                            SeatNumber = "S04",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000005"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 5,
                            Floor = 1,
                            RowNumber = 1,
                            SeatNumber = "S05",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000006"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 1,
                            Floor = 1,
                            RowNumber = 2,
                            SeatNumber = "S06",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000007"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 2,
                            Floor = 1,
                            RowNumber = 2,
                            SeatNumber = "S07",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000008"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 3,
                            Floor = 1,
                            RowNumber = 2,
                            SeatNumber = "S08",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000009"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 4,
                            Floor = 1,
                            RowNumber = 2,
                            SeatNumber = "S09",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000010"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 5,
                            Floor = 1,
                            RowNumber = 2,
                            SeatNumber = "S10",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000011"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 1,
                            Floor = 1,
                            RowNumber = 3,
                            SeatNumber = "S11",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000012"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 2,
                            Floor = 1,
                            RowNumber = 3,
                            SeatNumber = "S12",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000013"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 3,
                            Floor = 1,
                            RowNumber = 3,
                            SeatNumber = "S13",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000014"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 4,
                            Floor = 1,
                            RowNumber = 3,
                            SeatNumber = "S14",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000015"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 5,
                            Floor = 1,
                            RowNumber = 3,
                            SeatNumber = "S15",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000016"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 1,
                            Floor = 1,
                            RowNumber = 4,
                            SeatNumber = "S16",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000017"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 2,
                            Floor = 1,
                            RowNumber = 4,
                            SeatNumber = "S17",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000018"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 3,
                            Floor = 1,
                            RowNumber = 4,
                            SeatNumber = "S18",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000019"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 4,
                            Floor = 1,
                            RowNumber = 4,
                            SeatNumber = "S19",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000020"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 5,
                            Floor = 1,
                            RowNumber = 4,
                            SeatNumber = "S20",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000021"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 1,
                            Floor = 1,
                            RowNumber = 5,
                            SeatNumber = "S21",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000022"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 2,
                            Floor = 1,
                            RowNumber = 5,
                            SeatNumber = "S22",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000023"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 3,
                            Floor = 1,
                            RowNumber = 5,
                            SeatNumber = "S23",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000024"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 4,
                            Floor = 1,
                            RowNumber = 5,
                            SeatNumber = "S24",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000025"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 5,
                            Floor = 1,
                            RowNumber = 5,
                            SeatNumber = "S25",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000026"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 1,
                            Floor = 1,
                            RowNumber = 6,
                            SeatNumber = "S26",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000027"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 2,
                            Floor = 1,
                            RowNumber = 6,
                            SeatNumber = "S27",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000028"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 3,
                            Floor = 1,
                            RowNumber = 6,
                            SeatNumber = "S28",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000029"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 4,
                            Floor = 1,
                            RowNumber = 6,
                            SeatNumber = "S29",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000030"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 5,
                            Floor = 1,
                            RowNumber = 6,
                            SeatNumber = "S30",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000031"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 1,
                            Floor = 1,
                            RowNumber = 7,
                            SeatNumber = "S31",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000032"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 2,
                            Floor = 1,
                            RowNumber = 7,
                            SeatNumber = "S32",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000033"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 3,
                            Floor = 1,
                            RowNumber = 7,
                            SeatNumber = "S33",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000034"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 4,
                            Floor = 1,
                            RowNumber = 7,
                            SeatNumber = "S34",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000035"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 5,
                            Floor = 1,
                            RowNumber = 7,
                            SeatNumber = "S35",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000036"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 1,
                            Floor = 1,
                            RowNumber = 8,
                            SeatNumber = "S36",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000037"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 2,
                            Floor = 1,
                            RowNumber = 8,
                            SeatNumber = "S37",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000038"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 3,
                            Floor = 1,
                            RowNumber = 8,
                            SeatNumber = "S38",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000039"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 4,
                            Floor = 1,
                            RowNumber = 8,
                            SeatNumber = "S39",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000040"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 5,
                            Floor = 1,
                            RowNumber = 8,
                            SeatNumber = "S40",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000041"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 1,
                            Floor = 1,
                            RowNumber = 9,
                            SeatNumber = "S41",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000042"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 2,
                            Floor = 1,
                            RowNumber = 9,
                            SeatNumber = "S42",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000043"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 3,
                            Floor = 1,
                            RowNumber = 9,
                            SeatNumber = "S43",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000044"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 4,
                            Floor = 1,
                            RowNumber = 9,
                            SeatNumber = "S44",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("45000000-0000-0000-0000-000000000045"),
                            BusTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColumnNumber = 5,
                            Floor = 1,
                            RowNumber = 9,
                            SeatNumber = "S45",
                            Type = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Badge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDropoff")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPickup")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Domain.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("RouteId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@vexesystem.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$.N14FFcQMoCcN3OZvl3DkOMgSok1ocYfR2qyWMxVmlpuqUxxl20la",
                            PhoneNumber = "0123456789",
                            Role = "Admin",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Booking", b =>
                {
                    b.HasOne("Domain.Entities.Location", "DropoffPoint")
                        .WithMany()
                        .HasForeignKey("DropoffPointId");

                    b.HasOne("Domain.Entities.Location", "PickupPoint")
                        .WithMany()
                        .HasForeignKey("PickupPointId");

                    b.HasOne("Domain.Entities.Trip", "Trip")
                        .WithMany("Bookings")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DropoffPoint");

                    b.Navigation("PickupPoint");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.BookingDetail", b =>
                {
                    b.HasOne("Domain.Entities.Booking", "Booking")
                        .WithMany("BookingDetails")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("Domain.Entities.Bus", b =>
                {
                    b.HasOne("Domain.Entities.BusType", "BusType")
                        .WithMany("Buses")
                        .HasForeignKey("BusTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusType");
                });

            modelBuilder.Entity("Domain.Entities.Invoice", b =>
                {
                    b.HasOne("Domain.Entities.Booking", "Booking")
                        .WithOne("Invoice")
                        .HasForeignKey("Domain.Entities.Invoice", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.HasOne("Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Domain.Entities.RouteStop", b =>
                {
                    b.HasOne("Domain.Entities.Route", "Route")
                        .WithMany("RouteStops")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Location", "Location")
                        .WithMany("RouteStops")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Domain.Entities.Seat", b =>
                {
                    b.HasOne("Domain.Entities.Trip", "Trip")
                        .WithMany("Seats")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Domain.Entities.SeatTemplate", b =>
                {
                    b.HasOne("Domain.Entities.BusType", "BusType")
                        .WithMany()
                        .HasForeignKey("BusTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusType");
                });

            modelBuilder.Entity("Domain.Entities.Trip", b =>
                {
                    b.HasOne("Domain.Entities.Bus", "Bus")
                        .WithMany("Trips")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Route", "Route")
                        .WithMany("Trips")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Domain.Entities.Booking", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Domain.Entities.Bus", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Domain.Entities.BusType", b =>
                {
                    b.Navigation("Buses");
                });

            modelBuilder.Entity("Domain.Entities.Route", b =>
                {
                    b.Navigation("RouteStops");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Domain.Entities.Location", b =>
                {
                    b.Navigation("RouteStops");
                });

            modelBuilder.Entity("Domain.Entities.Trip", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
